/* modconfig.h.  Generated by configure.  */
/* define this to enable debug code for this module */
/* #undef DEBUG */

/* Version number of package */
#define MODULE_VERSION "3.0.0"

/* Major Version */
#define MODULE_MAJOR "3"

/* Minor Version */
#define MODULE_MINOR "0"

/* Revision */
#define MODULE_REV "0"

/* "Full Version" */
#define MOD_VERSION "3.0.0"
#define MOD_WIN32VER "3,0,0,0"
#define MOD_WIN32VERN 3,0,0
